#!/usr/bin/python

glyphs = (
  # key 1
  ('  *  ',
   '  *  ',
   ' *** ',
   '*****',
   ' * * ',
  ),
  # key 2
  ('* * *',
   ' * * ',
   '* * *',
   ' * * ',
   '* * *',
  ),
  # key 3
  ('    *',
   '   * ',
   '  *  ',
   ' *   ',
   '*    ',
  ),
  # key 4
  (' *** ',
   '*****',
   '* * *',
   '*   *',
   ' * * ',
  ),
  # key 5
  (' *** ',
   '* * *',
   '*****',
   ' * * ',
   '*   *',
  ),
  # key 6
  (' *   * ',
   '  * *  ',
   '*******',
   '  ***  ',
   ' *   * ',
  ),
  # key 7
  (' *** ',
   '* * *',
   '*****',
   '*****',
   '* * *',
  ),
  # key 8
  ('**** ',
   ' ****',
   '**** ',
   ' ****',
   '**** ',
  ),
  # key 9
  ('  *  ',
   '  *  ',
   '* * *',
   '  *  ',
   '* * *',
  ),
  # key 10
  ('*   *',
   ' * * ',
   '  *  ',
   ' * * ',
   '*   *',
  ),
  # key 11
  ('  *  ',
   ' *   ',
   '*****',
   '   * ',
   '  *  ',
  ),
  # key 12
  ('***  ',
   '* *  ',
   '* *  ',
   '* * *',
   '  ***',
  ),
  # key 13
  ('       ',
   '  ***  ',
   ' ***** ',
   '*******',
   ' * * * ',
  ),
  # key 14
  (' *   * ',
   '*     *',
   ' ***** ',
   '  ***  ',
   ' * * * ',
  ),
  # key 15
  ('*   *',
   ' *** ',
   '*****',
   '* * *',
   '** **',
  ),

  # key 16
  ('** **',
   '*****',
   '*****',
   ' *** ',
   '  *  ',
  ),
)

assert len(glyphs) == 16

def row2val(row):
  val = 0
  for c in row:
    val <<= 1
    if c == '*':
      val += 1
  return val

s2 = []
key = 1
for g in glyphs:
  assert len(g) == 5
  s1 = []
  s1.append('  ')
  for row in g:
    if len(row) == 5:
      row = ' ' + row + ' '
    s1.append('0x%02x,' % row2val(row))
  s1.append(' // key %d' % key)
  key += 1
  s2.append(''.join(s1))

print('// 7x5 bitmaps: generated by arcade_glyphs.py')
print('static const uint8_t glyphs[] = {')
print '\n'.join(s2)
print('};')
